
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballonapp
  labels:
    app: ballonapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ballonapp
  template:
    metadata:
      labels:
        app: ballonapp
    spec:
      containers:
        - name: ballonappcontainer
          image: balloncontainer.azurecr.io/balloonpoppinggame:latest
          imagePullPolicy: Always
          ports:  # Correct indentation here
            - containerPort: 80
